---
  # Site.yml to manage the ApacheTomcat Playbook.

  - hosts: all
    remote_user: root
    sudo: yes
    vars_files:
      - group_vars/main.yml
      - vars/main.yml
      - roles/common/vars/main.yml
      - roles/java/vars/main.yml
      - roles/tomcat/vars/main.yml


  - name: common server state tasks
    hosts: all
    remote_user: root
    sudo: yes
    roles:
      - common
    tags:
      - common

  - name: ensure Java is installed and configured
    hosts: all
    remote_user: root
    sudo: yes
    roles:
      - java
    tags:
      - java

  - name: ensure Tomcat is installed and configured
    hosts: all
    remote_user: root
    sudo: yes
    roles:
      - tomcat
    tags:
      - tomcat
