---
# tasks file for java

  - name: ensure Java is installed
    yum:
      name: "{{ java_version }}"
      state: present

  - name: print out the java version
    shell: /usr/bin/java -version
    register: result

  - debug: var=result
