---
# tasks file for tomcat

  - name: ensure Tomcat is installed
    yum:
      name: tomcat.noarch
      state: latest

  - name: print out Tomcat version
    shell: /usr/sbin/tomcat version
    register: result

  - debug: var=result

  - name: deploy the Tomcat sample app to verify
    copy:
      src: files/sample.war
      dest: /usr/share/tomcat/webapps/
      owner: root
      group: root
      mode: 0644

  - name: ensure Tomcat is started at boot time and always running
    service:
      name: tomcat
      state: started
      enabled: yes
